\context DrumStaff = "Huevo"
<<
	\set Staff.instrumentName = "Huevo"
	\set Staff.shortInstrumentName = "H."
	\set Score.skipBars = ##t
	\set Staff.printKeyCancellation = ##f
	\drummode {

		%\override NoteHead #'stencil = #ly:text-interface::print
		%\override NoteHead #'text = #(markup #:musicglyph "scripts.stopped")

		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
%% 5
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
%% 10
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
%% 15
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
%% 20
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
%% 25
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
		mar8 mar8 mar8 mar8 mar8 mar8 mar8^^ mar8  |
%% 30
		mar1^^  |
		\bar "|."

	}
>>
